<script lang="ts">
import { onMounted, onUnmounted, computed, watch, ref, reactive } from 'vue';
import { registerTrack, unregisterTrack, playTrack, togglePlay, addToQueue, state } from '../../player/player';
import { Parser } from '../../parser';
import type { MediaTrack, MediaEntryMirror } from '../../player/types';





export const handleMediaAction = async (type: string, id: string, host: string, action: string, trackData: Partial<MediaTrack> = {}): Promise<void> => {
  const trackCover = trackData.cover || (type === 'youtube' ? `https://img.youtube.com/vi/${id}/0.jpg` : '');

  const media: MediaTrack = { 
    author: trackData.author || 'post',
    permlink: trackData.permlink || '',
    subId: trackData.subId,
    title: trackData.title || 'Media Content',
    sources: [{ 
      type: type as any, 
      id, 
      host,
      thumb: trackCover 
    }],
    activeSourceIndex: 0,
    cover: trackCover,
    ...trackData 
  };
  if (action === 'play') {
    await playTrack(media);
  } else if (action === 'queue') {
    addToQueue(media);
  }
};

// Global listener for <forum-media> tags generated by Parser
if (typeof document !== 'undefined') {
  document.addEventListener('click', (e: MouseEvent) => {
    const target = e.target as HTMLElement;
    const forumMedia = target.closest('forum-media');
    if (forumMedia) {
      e.preventDefault();
      const d = (forumMedia as HTMLElement).dataset;
      const action = 'play'; // Default action for clicking the placeholder
      handleMediaAction(d.type!, d.id!, d.host!, action, {
        title: d.title,
        author: d.author,
        permlink: d.permlink,
        subId: d.group ? (Number(d.index) > 1 ? `${d.group}:${d.index}` : d.group) : `idx:${d.type}:${d.index}`,
        cover: d.cover
      });
    }
  });
}
</script>

<script setup lang="ts">
import { getTorrent, parseInfoHash } from '../../player/webtorrent-pool';
import { TR } from '../../translations';

// Global cache for this session to persist resolutions across component unmounts
const sunoCache = reactive<Record<string, { id: string, src: string, cover: string }>>({});
const t = (k: string): string => {
  if (props.t) return props.t(k);
  return TR[k] || k;
};

// WebTorrent card live status
const torrentStatus = ref<{ progress: string; downloadSpeed: number; numPeers: number } | null>(null);
const copied = ref(false);
let statusInterval: ReturnType<typeof setInterval> | null = null;

const getMagnetName = (uri: string) => {
  try {
    const params = new URLSearchParams(uri.replace('magnet:', ''));
    return params.get('dn') || '';
  } catch {
    return '';
  }
};

const getMagnetHash = (uri: string) => {
  const hash = parseInfoHash(uri);
  return hash ? hash.slice(0, 10) + '...' : '';
};

const copyMagnetLink = async (uri: string) => {
  try {
    await navigator.clipboard.writeText(uri);
    copied.value = true;
    setTimeout(() => { copied.value = false; }, 2000);
  } catch (err) {
    console.error('Failed to copy magnet link:', err);
  }
};

const formatSpeed = (bytesPerSec: number): string => {
  if (bytesPerSec === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytesPerSec) / Math.log(k));
  return parseFloat((bytesPerSec / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
};

const updateTorrentStatus = () => {
  const primary = trackData.value.sources[0];
  if (primary?.type === 'webtorrent') {
    const infoHash = parseInfoHash(primary.id);
    if (infoHash) {
      const snap = getTorrent(infoHash);
      if (snap) {
        torrentStatus.value = {
          progress: (snap.progress * 100).toFixed(1),
          downloadSpeed: snap.downloadSpeed,
          numPeers: snap.numPeers
        };
        return;
      }
    }
  }
  torrentStatus.value = null;
};

const startStatusPolling = () => {
  stopStatusPolling();
  const primary = trackData.value.sources[0];
  if (primary?.type === 'webtorrent') {
    updateTorrentStatus();
    statusInterval = setInterval(updateTorrentStatus, 1500);
  }
};

const stopStatusPolling = () => {
  if (statusInterval) {
    clearInterval(statusInterval);
    statusInterval = null;
  }
};

const props = withDefaults(defineProps<{
  media?: MediaTrack | string; // Can be a track object or raw URL
  title?: string;
  author?: string;
  permlink?: string;
  t?: (k: string) => string;
  mode?: 'card' | 'micro' | 'unvisible';
  hideButtons?: boolean;
  // Fallback data attributes from parser (for non-Vue content bridge)
  dataType?: string;
  dataId?: string;
  dataSrc?: string;
  dataCover?: string;
  dataHost?: string;
  dataTitle?: string;
  dataAuthor?: string;
  dataPermlink?: string;
  dataPending?: string | boolean;
  dataGroup?: string;
  dataIndex?: string | number;
}>(), {
  mode: 'micro',
  hideButtons: false
});

const emit = defineEmits<{
  openTopic: [post: { author: string; permlink: string }];
}>();

// Internal state for resolved data if we started as pending
const resolvedTrack = ref<MediaTrack | null>(null);
const isResolving = ref(false);
const lastResolvedId = ref<string | null>(null);
const isUnmounted = ref(false);

const isSunoUuid = (type: string, id: string) => type === 'audio' && id.length >= 32;

const trackData = computed<MediaTrack>(() => {
  // 1. Resolve base data (resolvedTrack > props.media > single props)
  let base: any = {};
  if (resolvedTrack.value) {
    base = { ...resolvedTrack.value };
  } else if (props.media) {
    if (typeof props.media === 'string') {
      const detected = Parser.detectMedia(props.media);
      if (detected) base = { ...detected };
    } else {
      base = { ...props.media };
    }
  } else {
    base = {
      type: (props.dataType as any) || 'audio',
      id: (props.dataId as any) || '',
      src: (props.dataSrc as any),
      cover: props.dataCover,
      host: props.dataHost,
      author: props.dataAuthor,
      permlink: props.dataPermlink,
      title: props.dataTitle,
      group: props.dataGroup,
      typeIndex: props.dataIndex
    };
  }
  
  const type = base.type || 'audio';
  const id = base.id || '';
  let src = base.src;
  let cover = base.cover;
  let mediaThumb = '';

  if (isSunoUuid(type, id)) {
    if (!src) src = `https://cdn1.suno.ai/${id}.mp3`;
    mediaThumb = `https://cdn2.suno.ai/image_large_${id}.jpeg`;
    if (!cover) cover = mediaThumb;
  }

  // Auto-generate YouTube thumbnail
  if (type === 'youtube') {
    mediaThumb = base.thumb || `https://img.youtube.com/vi/${id}/0.jpg`;
    if (!cover) cover = mediaThumb;
  }

  const author = props.dataAuthor || props.author || base.author || 'post';
  const permlink = props.dataPermlink || props.permlink || base.permlink || '';

  // STRATEGY: subId calculation
  const group = props.dataGroup || base.group || '';
  const typeIndex = props.dataIndex || base.typeIndex || 0;
  
  let subId = base.subId || '';
  if (!subId) {
    if (group) {
        subId = Number(typeIndex) > 1 ? `${group}:${typeIndex}` : group;
    } else {
        subId = `idx:${type}:${typeIndex}`;
    }
  }

  // Title logic: Prefer real titles over placeholders. 
  let title = base.title || props.title || props.dataTitle || '';
  if (!title || title === '(no title)' || title === 'Media Content') {
    if (props.title && props.title !== '(no title)') title = props.title;
    else if (props.dataTitle && props.dataTitle !== '(no title)') title = props.dataTitle;
    else if (base.title && base.title !== '(no title)') title = base.title;
    else title = 'Media Content';
  }

  // Mirror support: find ALL media if it's the first registration for this post
  // This ensures priorities work even in Micro mode.
  const mirrors: MediaEntryMirror[] = base.sources || [];
  if (mirrors.length === 0) {
     // If we were passed a single media object, use it as primary
     mirrors.push({ type, id, src, host: base.host || props.dataHost, thumb: mediaThumb, group, typeIndex: Number(typeIndex) });
  } else {
    // Ensure the primary source in mirrors has the generated thumb if missing
    mirrors.forEach(m => {
      if (m.id === id && m.type === type && !m.thumb) m.thumb = mediaThumb;
    });
  }

  const dataPending = base.pending || props.dataPending === 'true' || props.dataPending === true;
  const actuallyPending = dataPending && !src && !isSunoUuid(type, id) && type !== 'youtube';

  return {
    author, permlink, subId,
    title,
    cover: mediaThumb || cover,
    pending: !resolvedTrack.value && (isResolving.value || actuallyPending),
    sources: mirrors,
    activeSourceIndex: (typeof base.activeSourceIndex !== 'undefined') ? base.activeSourceIndex : -1
  };
});

// Self-resolution for pending tracks
const resolveIfNeeded = async () => {
  const primary = trackData.value.sources[0];
  const currentId = primary?.id;
  const currentType = primary?.type;
  if (!currentId || isResolving.value || !trackData.value.pending) return;
  if (lastResolvedId.value === currentId) return;

  // Immediate exit if it's already a full UUID or has a source - NO RESOLVING NEEDED
  if (isSunoUuid(currentType, currentId) || primary?.src) {
    lastResolvedId.value = currentId;
    return;
  }

  isResolving.value = true;
  try {
    const isSunoPending = currentType === 'audio' && trackData.value.pending;
    const isPeertubeNeeded = currentType === 'peertube' && !resolvedTrack.value;

    if (isSunoPending) {
       // Suno resolution via Proxy
      const url = `https://suno.com/s/${currentId}`;
      const proxyUrl = `https://patient-firefly-be68.dotevo.workers.dev/?url=${encodeURIComponent(url)}`;
      console.log(proxyUrl);
      const response = await fetch(proxyUrl);
      const text = await response.text();
      const uuidMatch = text.match(/song\/([a-f0-9-]{36})/i);
      if (uuidMatch) {
        const uuid = uuidMatch[1];
        const sunoCover = `https://cdn2.suno.ai/image_large_${uuid}.jpeg`;
        resolvedTrack.value = { 
          ...trackData.value, 
          sources: [{
            type: 'audio',
            id: uuid,
            src: `https://cdn1.suno.ai/${uuid}.mp3`,
            thumb: sunoCover
          }],
          cover: sunoCover,
          pending: false 
        };
        sunoCache[currentId] = { id: uuid, src: resolvedTrack.value.sources[0].src!, cover: sunoCover };
        lastResolvedId.value = currentId;
      }
    } else if (isPeertubeNeeded) {
      const host = primary?.host || 'blurt.media';
      const apiUrl = `https://${host}/api/v1/videos/${currentId}`;
      const proxyUrl = `https://patient-firefly-be68.dotevo.workers.dev/?url=${encodeURIComponent(apiUrl)}`;
      console.log(proxyUrl);
      const response = await fetch(proxyUrl);
      if (response.ok) {
        const data = await response.json();
        const cover = data.thumbnailPath ? `https://${host}${data.thumbnailPath}` : (data.previewPath ? `https://${host}${data.previewPath}` : null);
        if (cover) {
          resolvedTrack.value = { 
            ...trackData.value, 
            cover, 
            sources: trackData.value.sources.map(s => {
              if (s.id === currentId && s.type === currentType) return { ...s, thumb: cover };
              return s;
            }),
            pending: false 
          };
        }
      }
    }
  } catch (e) {
    console.warn('ForumMedia: Resolution failed', e);
  } finally {
    isResolving.value = false;
  }
};

let registeredId: string | null = null;
let registeredType: string | null = null;
let registeredSubId: string | undefined = undefined;

const syncTrack = () => {
  const primary = trackData.value.sources[0];
  // CRITICAL: Only register if we have a stable, non-pending ID
  const shouldRegister = primary?.id && !trackData.value.pending;
  
  if (shouldRegister) {
    if (registeredId && (registeredId !== primary.id || registeredType !== primary.type || registeredSubId !== trackData.value.subId)) {
      unregisterTrack(registeredId, registeredType!, props.author, props.permlink, registeredSubId);
    }
    registerTrack(trackData.value);
    registeredId = primary.id;
    registeredType = primary.type;
    registeredSubId = trackData.value.subId;
  } else if (registeredId) {
    // If it became pending or lost ID, unregister
    unregisterTrack(registeredId, registeredType!, props.author, props.permlink, registeredSubId);
    registeredId = null;
    registeredType = null;
    registeredSubId = undefined;
  }
};

onMounted(() => {
  console.log(`[ForumMedia] Mounted: ${props.author}/${props.permlink}/${trackData.value.subId} (Initial ID: ${trackData.value.sources[0]?.id}, Pending: ${trackData.value.pending})`);
  resolveIfNeeded().then(() => {
    if (isUnmounted.value) return;
    console.log(`[ForumMedia] Resolution finished for ${props.author}/${props.permlink}/${trackData.value.subId}. Final ID: ${trackData.value.sources[0]?.id}`);
    syncTrack();
    startStatusPolling();
  });
});

watch(() => [trackData.value.pending, trackData.value.sources[0]?.id, trackData.value.subId], (newVal, oldVal) => {
  if (isUnmounted.value) return;
  console.log(`[ForumMedia] Watch triggered: ${props.author}/${props.permlink}/${trackData.value.subId}. Old: ${oldVal}, New: ${newVal}`);
  syncTrack();
  startStatusPolling();
});

onUnmounted(() => {
  isUnmounted.value = true;
  stopStatusPolling();
  if (registeredId && registeredType) {
    unregisterTrack(registeredId, registeredType, trackData.value.author, trackData.value.permlink, registeredSubId);
  }
});

const isActive = computed(() => {
  const current = state.currentTrack;
  if (!current) return false;
  return (current.author === trackData.value.author && current.permlink === trackData.value.permlink && current.subId === trackData.value.subId);
});

const isCurrentSourceActive = computed(() => {
  if (!isActive.value) return false;
  const current = state.currentTrack;
  if (!current) return false;
  const activeSrc = current.sources[current.activeSourceIndex || 0];
  const thisSrc = trackData.value.sources[0];
  return activeSrc?.id === thisSrc?.id && activeSrc?.type === thisSrc?.type;
});

const isPlaying = computed(() => isCurrentSourceActive.value && state.playing);

const handlePlay = async () => {
  if (isResolving.value) return;
  if (trackData.value.pending) await resolveIfNeeded();
  
  if (isCurrentSourceActive.value) {
    togglePlay();
  } else {
    // Card mode = Manual (this source)
    // Micro mode = Auto (best source from registry)
    await playTrack(trackData.value, props.mode === 'card');
  }
};

const handleQueue = () => {
  if (trackData.value.pending || isResolving.value) return;
  addToQueue(trackData.value);
};

const thumbUrl = computed(() => trackData.value.cover || '');
const displayHost = computed(() => {
  const primary = trackData.value.sources[0];
  return primary?.host || (primary?.type === 'audio' ? 'suno' : primary?.type);
});

const selectInputText = (event: Event) => {
  const target = event.target as HTMLInputElement | null;
  if (target) {
    target.select();
  }
};

</script>

<template>
  <template v-if="mode === 'unvisible'"></template>
  <div 
    v-else
    class="forum-media-container" 
    :class="[`mode-${mode}`, { 'is-active': isActive, 'is-playing': isPlaying }]"
  >
    <!-- MICRO MODE (Default for posts) -->
    <template v-if="mode === 'micro'">
      <div class="forum-media-micro">
        <slot>
          <template v-if="!hideButtons">
            <span class="media-icon" @click.stop="handlePlay" :title="trackData.title" :class="{ 'is-active': isActive, 'is-playing': isPlaying }">
              <i v-if="isResolving" class="fa-solid fa-spinner fa-spin"></i>
              <template v-else>
                <i v-if="isActive && !isCurrentSourceActive" class="fa-solid fa-shuffle"></i>
                <i v-else :class="isPlaying ? 'fa-solid fa-pause' : (trackData.sources[0]?.type === 'audio' ? 'fa-solid fa-music' : 'fa-solid fa-circle-play')"></i>
              </template>
            </span>
            <span class="media-icon" @click.stop="handleQueue">
              <i class="fa-solid fa-plus"></i>
            </span>
          </template>
        </slot>
      </div>
    </template>

    <!-- CARD MODE (Explicit cards) -->
    <template v-else-if="mode === 'card'">
      <!-- WebTorrent Custom Card -->
      <div 
        v-if="trackData.sources[0]?.type === 'webtorrent'"
        class="webtorrent-card" 
        :class="{ 'is-active': isActive, 'is-playing': isPlaying }"
      >
        <div class="wt-header">
          <span class="wt-icon"><i class="fa-solid fa-magnet"></i></span>
          <div class="wt-info">
            <div class="wt-title">
              {{ trackData.title && trackData.title !== 'Media Content' ? trackData.title : (getMagnetName(trackData.sources[0].id) || 'WebTorrent') }}
            </div>
            <div class="wt-hash gs">{{ t('hash') }}: {{ getMagnetHash(trackData.sources[0].id) }}</div>
          </div>
        </div>
        
        <!-- Live Download Status -->
        <div v-if="torrentStatus" class="wt-download-stats">
          <div class="wt-progress-bar">
            <div class="wt-progress-fill" :style="{ width: torrentStatus.progress + '%' }"></div>
          </div>
          <div class="wt-stats-row gs">
            <span>{{ torrentStatus.progress }}%</span>
            <span>{{ t('downloadSpeed') }}: {{ formatSpeed(torrentStatus.downloadSpeed) }}</span>
            <span>{{ t('peers') }}: {{ torrentStatus.numPeers }}</span>
          </div>
        </div>

        <div class="wt-actions">
          <button class="btn btn-primary btn-sm" @click.stop="handlePlay" :disabled="trackData.pending">
            <i :class="isPlaying ? 'fa-solid fa-pause' : 'fa-solid fa-play'"></i>
            <span>{{ isPlaying ? 'Pause' : t('playTorrent') }}</span>
          </button>
          <button class="btn btn-ghost btn-sm" @click.stop="handleQueue" :disabled="trackData.pending">
            <i class="fa-solid fa-plus"></i> <span>Queue</span>
          </button>
          <button class="btn btn-ghost btn-sm" @click.stop="copyMagnetLink(trackData.sources[0].id)">
            <i class="fa-solid" :class="copied ? 'fa-circle-check' : 'fa-copy'"></i> 
            <span>{{ copied ? t('copied') : t('copyMagnet') }}</span>
          </button>
        </div>

        <!-- Magnet Link box -->
        <div class="wt-link-box">
          <input 
            type="text" 
            readonly 
            :value="trackData.sources[0].id" 
            class="wt-magnet-input" 
            @click.stop="selectInputText($event)" 
          />
        </div>
      </div>

      <!-- General Media Card -->
      <div 
        v-else
        class="media-placeholder" 
        :class="{ 'is-resolving': trackData.pending, 'no-thumb': !thumbUrl }"
        :style="thumbUrl ? `background-image: url(${thumbUrl})` : ''"
        @click="handlePlay"
      >
        <div class="media-placeholder-overlay">
          <div class="media-placeholder-actions">
            <button class="btn btn-primary" @click.stop="handlePlay" :disabled="trackData.pending">
              <i v-if="trackData.pending" class="fa-solid fa-spinner fa-spin"></i>
              <template v-else>
                <i :class="isPlaying ? 'fa-solid fa-pause' : (isActive && !isCurrentSourceActive ? 'fa-solid fa-shuffle' : 'fa-solid fa-play')"></i> 
                <span class="btn-text">
                  {{ isPlaying ? 'Pause' : (isActive && !isCurrentSourceActive ? 'Switch' : 'Play') }}
                </span>
              </template>
            </button>
            <button class="btn btn-ghost" @click.stop="handleQueue" :disabled="trackData.pending">
              <i class="fa-solid fa-plus"></i> <span class="btn-text">Queue</span>
            </button>
          </div>
          <div class="source-label">{{ displayHost }}</div>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
/* Re-inject essential global styles for Shadow DOM */
.btn {
  padding: 6px 14px;
  font-size: 13px;
  font-weight: bold;
  cursor: pointer;
  border: 1px solid var(--input-border, #999);
  background: var(--input-bg, #fff);
  color: var(--text, #333);
  border-radius: 4px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  text-decoration: none;
  transition: all 0.2s;
}
.btn:hover { background: var(--bg-white, #fff); border-color: var(--primary, #006699); color: var(--primary, #006699); }
.btn-primary { background: var(--primary, #006699); color: #fff; border-color: var(--primary-dk, #005580); }
.btn-primary:hover { background: var(--primary-lt, #0076B1); color: #fff; }
.btn-ghost { background: transparent; color: var(--primary, #006699); border: 1px solid var(--primary, #006699); }
.btn-ghost:hover { background: var(--primary, #006699); color: #fff; }
.btn:disabled { opacity: .5; cursor: default; }

.forum-media-container {
  display: block;
  width: 100%;
  max-width: 100%;
  box-sizing: border-box;
}

.mode-micro.forum-media-container {
  display: inline-block;
  vertical-align: middle;
  width: auto;
}

.forum-media-micro {
  display: flex;
  align-items: center;
  gap: 4px;
}

.media-icon {
  cursor: pointer;
  color: var(--primary, #006699);
  opacity: 0.7;
  transition: opacity 0.2s;
  font-size: 14px;
}
.media-icon:hover { opacity: 1; }

.forum-media-container.mode-card {
  display: block;
  width: 100%;
  max-width: 100%;
  clear: both;
}

.media-placeholder {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  background-color: #000;
  background-size: cover;
  background-position: center;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid var(--border-main, #98AAB1);
  box-sizing: border-box;
  cursor: pointer;
}

.media-placeholder-overlay {
  position: absolute;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  opacity: 0.9;
  transition: opacity 0.3s;
}

.media-placeholder-actions {
  display: flex;
  gap: 12px;
  justify-content: center;
  width: 100%;
  padding: 0 10px;
  box-sizing: border-box;
}

.source-label {
  position: absolute;
  bottom: 10px;
  right: 12px;
  font-size: 10px;
  text-transform: uppercase;
  color: #fff;
  opacity: 0.8;
  background: rgba(0,0,0,0.4);
  padding: 2px 6px;
  border-radius: 4px;
}

.media-placeholder.is-resolving {
  filter: grayscale(0.5);
  cursor: wait;
  animation: bfp-resolving-pulse 2s infinite ease-in-out;
}
@keyframes bfp-resolving-pulse {
  0% { opacity: 0.8; }
  50% { opacity: 0.4; }
  100% { opacity: 0.8; }
}

@media (max-width: 800px) {
  .media-placeholder-actions {
    flex-direction: column;
    gap: 8px;
    align-items: center;
  }
  .btn {
    width: 100%;
    max-width: 160px;
  }
  .btn-text { display: inline; }
}

.webtorrent-card {
  background: var(--nav-bg, rgba(20, 30, 40, 0.05));
  border: 1px solid var(--border-main, #98AAB1);
  border-radius: 8px;
  padding: 14px;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 100%;
}
.webtorrent-card.is-active {
  border-color: var(--accent, #e74c3c);
  box-shadow: 0 0 8px rgba(231, 76, 60, 0.15);
}
.wt-header {
  display: flex;
  align-items: center;
  gap: 12px;
}
.wt-icon {
  font-size: 24px;
  color: var(--accent, #e74c3c);
  opacity: 0.9;
}
.wt-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
  overflow: hidden;
}
.wt-title {
  font-weight: bold;
  font-size: 13px;
  color: var(--text, #333);
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
.wt-hash {
  font-size: 10px;
  opacity: 0.6;
}
.wt-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
.btn-sm {
  padding: 4px 10px;
  font-size: 11px;
}
.wt-link-box {
  width: 100%;
}
.wt-magnet-input {
  width: 100%;
  padding: 6px 10px;
  font-size: 11px;
  border: 1px solid var(--border-main, #ccc);
  background: var(--bg-page, #f9f9f9);
  color: var(--text, #666);
  border-radius: 4px;
  box-sizing: border-box;
  text-overflow: ellipsis;
}
.wt-progress-bar {
  width: 100%;
  height: 6px;
  background: rgba(0,0,0,0.1);
  border-radius: 3px;
  overflow: hidden;
}
.wt-progress-fill {
  height: 100%;
  background: var(--primary, #006699);
  transition: width 0.3s;
}
.wt-stats-row {
  display: flex;
  justify-content: space-between;
  font-size: 11px;
  margin-top: 4px;
}

@media (max-width: 480px) {
  .forum-media-container.mode-card {
    max-width: calc(100vw - 32px);
  }
}
</style>
